### ISSUE TITLE
Conflict with ReportPortal Cypress agent. Not able to take screenshot - The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

### ISSUE THREAD

**Issue by akbarchandani** [Visual-Regression-Tracker/Visual-Regression-Tracker#249]
While running VRTwith our cypress automation framework. We are seeing the below issue:

cy.task('ENCODE_IMAGE') failed with the following error:

> The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

below is the agent version:
 "@visual-regression-tracker/agent-cypress": "^4.7.3"

below is the option details:
cy.vrtTrack("Whole page");

cypress version:
"cypress": "^6.4.0"

I am unable to attach my cypress.json file below is the cypress.json config information.

{
  "reporterOptions": {
    "endpoint": "https://reportportal.xxx.xxx.com/api/v1",
    "token": "XXX-XXXX-XXXX-CXXX0",
    "launch": "Kolmeo_Cypres_Web_Regression",
    "project": "automation_web_cy",
    "description": "Kolmeo_Cypres_Web_Smoke_Test",
    "autoMerge": false
  },

  "chromeWebSecurity": false,
  "testFiles": ["**/*.feature"],
  "projectId": "XXXXXXX",
  "defaultCommandTimeout": 20000,
  "videoUploadOnPasses": false
}

Look forward to your response.

**Please note:** I am able to run the cypress agent example on my local without any issues.

**Comment by pashidlos** [comment]
@akbarchandani it's happening due to cypress native screenshot command is overwritten by reportportal agent here
https://github.com/reportportal/agent-js-cypress/blob/master/lib/commands/reportPortalCommands.js#L164
seems like they are not passing all arguments or it's cypress issue

could you check if screenshot command is working itself?
this should take an image and save it in cypress folder
```
cy.screenshot("Some name");
```

if it doesn't work then we should rise issue to RP plugin as they override screenshot function incorrectly

**Comment by pashidlos** [comment]
depends on: https://github.com/reportportal/agent-js-cypress/issues/76

**Comment by akbarchandani** [comment]
Thanks, much appreciated.


Kind regards,


Akbar Chandani

________________________________
