### ISSUE TITLE
Screenshot backup / Integration with Git 

### ISSUE THREAD

**Issue by priyankachaturvedi30** [Visual-Regression-Tracker/Visual-Regression-Tracker#250]
Is there a possibility through which we can use git for Version Controlling. If so, would it require to maintain database along with image backup in Git? This is more of an enhancement that I propose to maintain baselines. On similar lines of #244

**Comment by pashidlos** [comment]
not sure how to do this using SAAS approach
this could be achieved storing baselines alongside the code and use some library to compare images

**Comment by priyankachaturvedi30** [comment]
@pashidlos : I don't get you. Can you help me understand what exactly are you suggesting?

**Comment by pashidlos** [comment]
@priyankachaturvedi30 having images and app code in different places it's not possible to use git 
only when images are stored together inside the app repo

**Comment by suratdas** [comment]
Backup of baseline images: In my past project where I was using ImageMagick, the baseline images were named with the testCase_Screen name instead of timestamp and I mapped the image folder to a git server repo and we're uploading those baselines to the git server through the command line. With VRT, the image file names are timestamp-based, and not easy to know which files refer to which test.

**Comment by pashidlos** [comment]
@suratdas if we decide to change naming we would need to include whole variation (name+os+device+viewport+browser+branch) and it could be more than that with custom tags feature that is planned in backlog 

@priyankachaturvedi30 could you elaborate benefits of this?
