### ISSUE TITLE
VRT installation is failing with invalid tag format

### ISSUE THREAD

**Issue by rafitur2** [Visual-Regression-Tracker/Visual-Regression-Tracker#365]
VRT installation is failing with invalid tag format:

 ./vrt-install.sh

Downloading docker files

Applying configuration
JWT secret: yRkcA9dIOHCd8TDTUmhoZRXtZ4gLxxxx

Starting docker
Pulling ui (visualregressiontracker/ui:${VRT_VERSION})...
ERROR: invalid tag format

**Comment by rafitur2** [comment]
Hi @pashidlos 
env file is getting generated automatically, I have shared the steps to reproduce + the default env file.

**Steps to reproduce: :** 
[docker@ilcepocx ~]$ curl https://raw.githubusercontent.com/Visual-Regression-Tracker/Visual-Regression-Tracker/master/vrt-install.sh -o vrt-install.sh

[docker@ilcepocx ~]$ ./vrt-install.sh

Downloading docker files

Applying configuration
JWT secret: fZI918G82TxhjCtnNJ8bLss9YVKTNw2J

Starting docker
Pulling ui (visualregressiontracker/ui:${VRT_VERSION})...
**ERROR: invalid tag format**


**ENV file  :**

[docker@ilcepocx ~]$ more .env
## Logging
ELK_VERSION=7.14.1
ELASTIC_URL=http://localhost:9200

## VRT version
VRT_VERSION=4.20.3
VRT_UI_VERSION=${VRT_VERSION}
VRT_API_VERSION=4.20.2
VRT_MIGRATION_VERSION=4.20.1

## Frontend

# direct URL to backend with port (same as APP_PORT)
REACT_APP_API_URL=http://localhost:4200
# frontend port
PORT=8080

## Backend

# direct URL to frontend with port (same as PORT)
APP_FRONTEND_URL=http://localhost:8080
# backend port
APP_PORT=4200
# seed to generate JWT
JWT_SECRET=fZI918G82TxhjCtnNJ8bLss9YVKTNw2J
# user session lifetime
JWT_LIFE_TIME=1d
# max image size to upload
BODY_PARSER_JSON_LIMIT="5mb"

## DB

POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=vrt_db
[docker@ilcepoc1743 ~]$

**Comment by pashidlos** [comment]
I see that value for version is not replaced
what is your OS?
try without the script starting docker directly

**Comment by rafitur2** [comment]
After using the below command, there is a progress, but one error is thrown by the end of the installation.

Command: docker-compose up

Results:

cbdbe7a5bc2a: Already exists
6282c10629b6: Already exists
24f383844fee: Already exists
22e94daf4797: Already exists
ba5813ec655d: Pull complete
8b907c974aea: Pull complete
ce0d04bf51de: Pull complete
Creating docker_ui_1       ... done
Creating docker_postgres_1 ... done
Creating docker_api_1      ... done

ERROR: for migration  Container "bf424eb16778" is unhealthy.
ERROR: Encountered errors while bringing up the project.

My OS is:
    Virtualization: vmware
  Operating System: Red Hat Enterprise Linux
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.6:GA:server
            Kernel: Linux 3.10.0-957.el7.x86_64
      Architecture: x86-64

**Comment by pashidlos** [comment]
@rafitur2 remove all images and containers and try again

**Comment by jsmythsci** [comment]
I seem to have the same issue doing manual installation on Ubuntu 20.04.

Steps to reproduce:

1. Copy [docker-compose.yml](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/blob/master/docker-compose.yml)
`$ curl https://raw.githubusercontent.com/Visual-Regression-Tracker/Visual-Regression-Tracker/master/docker-compose.yml -o docker-compose.yml`

2. Copy [.env](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/blob/master/.env)
`$ curl https://raw.githubusercontent.com/Visual-Regression-Tracker/Visual-Regression-Tracker/master/.env -o .env`

3. Update .env
`$ sed -i~ 's/localhost/my.host.name/g' .env`

4. Start service
`$ docker-compose up`

Expected result: All containers start successfully.

Actual result: startup fails, throwing an invalid tag format error:

```
jasons@camasvvrt1:/opt/vrt$ sudo docker-compose up
Creating network "vrt_default" with the default driver
ERROR: no such image: visualregressiontracker/ui:${VRT_VERSION}: invalid reference format
```

The issue seems to result from Docker Compose not recursively resolving `VRT_UI_VERSION` within the `.env` file. Replacing the nested variable reference allows the containers to start normally:

```
jasons@camasvvrt1:/opt/vrt$ sudo docker-compose up
Creating network "vrt_default" with the default driver
ERROR: no such image: visualregressiontracker/ui:${VRT_VERSION}: invalid reference format
jasons@camasvvrt1:/opt/vrt$ sudo sed -i 's/\${VRT_VERSION}/4.20.3/' .env
jasons@camasvvrt1:/opt/vrt$ sudo docker-compose up
Pulling ui (visualregressiontracker/ui:4.20.3)...
4.20.3: Pulling from visualregressiontracker/ui
3d2430473443: Pull complete
4ba4f346920e: Pull complete
6c53e58c6af6: Pull complete
...
```

I would be happy to submit a PR to fix this, but I don't know enough about Docker Compose to know whether or not it is supposed to be able to recursively resolve variables like this.

I found [this Issue](https://github.com/docker/compose/issues/8286) that looks to be somewhat related, but the examples there are all more complex than what is used in the file here.
