### ISSUE TITLE
Doesn't change imageOptions[] in test

### ISSUE THREAD

**Issue by Elverslane** [Visual-Regression-Tracker/Visual-Regression-Tracker#4]
### Hello! I just tried your app and its very interesting and I found some issues. There is one of them:

In example we have `const imageOptions = {}` which I suppose should influence on browser config and env. 
But if I changes this options in current test stays default settings and only text in web changes like this:
<img width="1178" alt="Снимок экрана 2020-05-20 в 13 41 44" src="https://user-images.githubusercontent.com/17493900/82437361-ee7f0200-9a9f-11ea-8146-9857c49c3c2f.png">

Maybe I do something wrong?

**Comment by pashidlos** [comment]
in JS example `imageOptions` is representing current setup rather than setting it up 
so it's used as a metadata for screenshoot but doesn't change Playwright configuration 

if you want to take images in another browser and/or viewport:
1. change setting for browser automation tool (here is how to change viewport size in [Playwright](https://github.com/microsoft/playwright/blob/master/docs/api.md#browsernewcontextoptions))
2. provide this information when you are sending image
```
 await vrt.track({
            name: "Search page",
            imageBase64: (await page.screenshot()).toString('base64'),
            {
                 browser: "any browser",
                 viewport: "1800x1600",
            }
        });
```
this information helps to distinguish the same page image but taken in different browser/os/viewport variations

**Comment by Elverslane** [comment]
I see
provide params like this resolved my problem
`const context = await browser.newContext({
            viewport: {
                height: 100,
                width: 192,
            }
        });`
