### ISSUE TITLE
Failed test with 500 error

### ISSUE THREAD

**Issue by Elverslane** [Visual-Regression-Tracker/Visual-Regression-Tracker#5]
After few launches I have this error:
<img width="1512" alt="Снимок экрана 2020-05-20 в 13 47 28" src="https://user-images.githubusercontent.com/17493900/82440508-1d4ba700-9aa5-11ea-8f66-e775565e507a.png">

container logs: 
<img width="1356" alt="Снимок экрана 2020-05-20 в 14 23 33" src="https://user-images.githubusercontent.com/17493900/82440761-88957900-9aa5-11ea-96a0-faa1ba71fe5c.png">

sometimes helps restart docker image

**Comment by pashidlos** [comment]
could you share code for your test that cause first error?

the reason for second error could be because in DB you have reference on image that does not exists anymore try:
`docker exec -it CONTAINER_NAME sh`
`cd imageUploads`
if there is no image with that name it's more warning that critical error 

when you delete container that runs backend application all images gets removed as well 
in order to persist your images you could add volume in `docker-compose.yml` for `api` service

```
volume:
   - ./imageUploads:/${IMG_UPLOAD_FOLDER}
```
this maps your local folder `imageUploads` to the one in container

**Comment by pashidlos** [comment]
my bad, images are cleaned every time container is restarted
gonna fix it

**Comment by pashidlos** [comment]
1. copy updated [docker-compose.yml](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/blob/master/docker-compose.yml)
1. Create folder for images `imageUploads`

please, reopen if not fixed

**Comment by Elverslane** [comment]
its kinda strange but I've done two steps above and after some time got same error with same screenshot name
`api_1        | [Nest] 18   - 05/20/2020, 8:12:48 PM   [ExceptionsHandler] ENOENT: no such file or directory, open '/imageUploads/1589969723915.screenshot.png' +16997ms`

**Comment by pashidlos** [comment]
the problem is that baseline still recorder in DB 
you could:
- remove it manually from DB
- remove project and create new one

as you already have containers created you need to recreate them to have new volume mounted
`docker-compose up --force-recreate`

**Comment by Elverslane** [comment]
its work! ty!

**Comment by pashidlos** [comment]
thanks for the report!
